### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by lly-c232733** [openziti/ziti-browzer-bootstrapper#237]
Hello, I get this error when trying docker install ( note, to get the error I needed to alter the uncaught exception event in index.js to 'console.log(e)' instead of 'logger.error(e)' because the error happens before the logger is created )

Error: EACCES: permission denied, mkdir 'log'
    at Object.mkdirSync (node:fs:1382:3)
    at createLogger (/home/node/ziti-browzer-bootstrapper/index.js:204:12)
    at main (/home/node/ziti-browzer-bootstrapper/index.js:705:14)
    at Object.<anonymous> (/home/node/ziti-browzer-bootstrapper/index.js:756:1)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: 'log'

For docker I tried 

GitHub instructions
user 1000:2171

My uid is 1001 on docker host
user 1001:2171

Openziti.io instructions, my UID ends up not being set.
user ${UID}:2171

Just tried this (I'm following guide on openziti.io)
user 2171:2171

I tried not setting a user, and that seems to work, but I get a self signed certificate error (could that be related to permissions?)

I am not setting the environment variable 'ZITI_BROWZER_BOOTSTRAPPER_LOG_PATH'

**Comment by lly-c232733** [comment]
Ignore, user ${uid}:2171 worked after reboot
