### ISSUE TITLE
Mixed-case in vhost field of targetArray leads to exceptions

### ISSUE THREAD

**Issue by rentallect** [openziti/ziti-browzer-bootstrapper#264]
In `0.59.1`:

TypeError: Cannot read properties of undefined (reading 'vhost')
 at Object.common.generateZitiConfigObject (/home/node/ziti-browzer-bootstrapper/lib/http-proxy/common.js:307:29)
 at ServerResponse.res.writeHead (/home/node/ziti-browzer-bootstrapper/lib/inject.js:109:33)
 at Array.stream (/home/node/ziti-browzer-bootstrapper/lib/http-proxy/passes/web-incoming-zitified.js:658:9)
 at ProxyServer.<anonymous> (/home/node/ziti-browzer-bootstrapper/lib/http-proxy/index.js:90:21)
 at /home/node/ziti-browzer-bootstrapper/index.js:644:15
 at Layer.handle [as handle_request] (/home/node/ziti-browzer-bootstrapper/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/home/node/ziti-browzer-bootstrapper/node_modules/express/lib/router/index.js:328:13)
 at /home/node/ziti-browzer-bootstrapper/node_modules/express/lib/router/index.js:286:9
 at Function.process_params (/home/node/ziti-browzer-bootstrapper/node_modules/express/lib/router/index.js:346:12)
 at next (/home/node/ziti-browzer-bootstrapper/node_modules/express/lib/router/index.js:280:10)

**Comment by rentallect** [comment]
fixed in `0.60.0`
